services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
